language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY=2.8.*
  - SYMFONY=""
  - SYMFONY=dev-master
matrix:
  fast_finish: true
  allow_failures:
    - env: SYMFONY=dev-master

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update
  - if [ "$SYMFONY" != "" ]; then composer require "symfony/symfony:${SYMFONY}" --no-update; fi;

install:
  - composer update --prefer-dist --no-interaction ${COMPOSER_FLAGS}

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - bin/phpunit

notifications:
  on_success: never
  on_failure: always
